version: '3'
services:
  webdav:
    #image: bytemark/webdav
    build:
      dockerfile: Dockerfile2
    container_name: webdav
    restart: always
    environment:
      AUTH_TYPE: Digest
      USERNAME: frodo
      PASSWORD: bolson
    volumes:
      - /docker/files:/var/lib/dav
    depends_on:
      - nginx

  nginx:
    build:
      dockerfile: Dockerfile
    container_name: proxy
 #   volumes:
 #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8888:80